config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#index'
  get 'static_pages/secret'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
	#after_create :confirmation_send

  belongs_to :participant, class_name: 'User'
  belongs_to :event

  private

  def confirmation_send
    AttendanceMailer.confirmation_email(self).deliver_now
  end
end

app/models/event.rb
class Event < ApplicationRecord
#	after_create :confirmation_send
	
  belongs_to :admin, class_name: 'User'
  has_many :attendances
  has_many :participants, class_name: 'User', through: :attendances

  #validates :start_date, presence: true, start_date: true
  #validates :duration, presence: true, duration: true
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0, less_than_or_equal_to: 1000 }
  validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send

	has_many :events, foreign_key: 'admin_id', class_name: 'Event'
  has_many :attendances, foreign_key: 'participant_id', class_name: 'Attendance'
  
  private

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_devise_parameters, if: :devise_controller?

	def configure_devise_parameters
		devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
		devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  before_action :authenticate_user!, only: [:secret]


  def index
  end

  def secret
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Event</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
 <nav class="navbar navbar-expand-lg sticky-top navbar-light" style="background-color: #e3f2fd;">
      <div class="navbar-brand"><%= link_to "Home", root_path %></div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto">
         
          <% if user_signed_in?%>
              <li class='nav-item'>
                <div class="navbar-link">
                  <div class="dropdown">
                    <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      My profil
                    </button>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                      <a class="dropdown-item color-black" href="<%=new_user_session_path(current_user.id)%>"><p>See my profil</p></a>
                      <a class="dropdown-item color-black" href="<%=edit_user_registration_path%>"><p>Edit my password/email</p></a>
                     
                    </div>
                  </div>
                </div>
              </li>
          <% end %>
        </ul>

        <%unless user_signed_in? %>
          <div class='flex-row'>
                       <div class="navbar-text">
              <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Login/Signup
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                  <a class="dropdown-item color-black" href="<%=new_user_registration_path%>"><p>Sign in</p></a>
                  <a class="dropdown-item color-black" href="<%=new_user_session_path%>"><p>Login</p></a>
                </div>
              </div>
            </div>
          </div>
        <%else%>
          <div class='flex'>
            
            <span class="navbar-text">
                <p><%=current_user.email%></p>
            </span>
            <span class="navbar-text">
              <%= link_to"Disconnect", destroy_user_session_path , method: :delete, class:"btn btn-danger"%>
            </span>
          </div>
        <%end%>
      </div>
    </nav>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<h1>Bienvenue</h1>
<p>
  <% if user_signed_in? %>
    <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>
      <li>
      Voici ton email : <%= current_user.email %>
    </li>

    <li>
      <%= link_to "Secret page", static_pages_secret_path %>
    </li>

    <li>
      <%= link_to "Edit email / password", edit_user_registration_path %>
    </li>

  <% else %>
    <%= link_to "S'inscrire", new_user_registration_path %>

	<%= link_to 'Se connecter', new_user_session_path %>
  <% end %>	
</p>

app/views/static_pages/secret.html.erb
<h1>StaticPages#secret</h1>
<p>Find me in app/views/static_pages/secret.html.erb</p>